# Generated by Django 4.2.17 on 2024-12-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('visitors_count', models.IntegerField(verbose_name='Количество посетителей')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка')),
                ('event_count', models.IntegerField(verbose_name='Количество мероприятий')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'db_table': 'statistics',
                'ordering': ['-date'],
            },
        ),
    ]
