# Generated by Django 4.2.17 on 2024-12-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя животного')),
                ('species', models.CharField(max_length=100, verbose_name='Вид')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('health_status', models.CharField(max_length=50, verbose_name='Состояние здоровья')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('diet', models.TextField(verbose_name='Рацион питания')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение в зоопарке')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'db_table': 'animals',
            },
        ),
    ]
