# Generated by Django 4.2.17 on 2024-12-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('department', models.CharField(max_length=100, verbose_name='Отдел')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('schedule', models.CharField(max_length=100, verbose_name='График работы')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
    ]
